apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-config
data:
  AUTH_SERVICE_URL: "http://auth-service:8081"
  USER_SERVICE_URL: "http://user-service:8082"
  ADMIN_SERVICE_URL: "http://admin-service:8082"
  EMPLOYEE_SERVICE_URL: "http://employee-service:8083"
  CUSTOMER_SERVICE_URL: "http://customer-service:8084"
  HR_SERVICE_URL: "http://hr-service:8085"
  TASK_SERVICE_URL: "http://task-service:8089"
